In [ ]:
!pip install -U psycopg2-binary sqlalchemy pandas datasets peft torchao transformers sentencepiece sacremoses accelerate evaluate sacrebleu

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-4.8.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.19.1)
Requirement already satisfied: torchao in /usr/local/lib/python3.12/dist-packages (0.10.0)
Collecting torchao
  Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (20 kB)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.7.0-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)
Collecting sacremoses
  Downloading sacremoses-0.1.1-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.13.0)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting sacrebleu
  Downloading sacrebleu-2.6.0-py3-none-any.whl.metadata (39 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.2.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.10.0+cu128)
Requirement already satisfied: safetensors in /usr/local/lib/python3.12/dist-packages (from peft) (0.7.0)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from sacremoses) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from sacremoses) (1.5.3)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.1.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch>=1.13.0->peft) (1.5.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.13.0->peft) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 40.2 MB/s eta 0:00:00
Downloading pandas-3.0.2-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 70.9 MB/s eta 0:00:00
Downloading datasets-4.8.5-py3-none-any.whl (528 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 529.0/529.0 kB 27.1 MB/s eta 0:00:00
Downloading torchao-0.17.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 76.7 MB/s eta 0:00:00
Downloading transformers-5.7.0-py3-none-any.whl (10.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.5/10.5 MB 79.3 MB/s eta 0:00:00
Downloading sacremoses-0.1.1-py3-none-any.whl (897 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 897.5/897.5 kB 49.5 MB/s eta 0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 7.2 MB/s eta 0:00:00
Downloading sacrebleu-2.6.0-py3-none-any.whl (100 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.8/100.8 kB 7.7 MB/s eta 0:00:00
Downloading pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 MB 15.9 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Installing collected packages: torchao, sacremoses, pyarrow, psycopg2-binary, portalocker, colorama, sacrebleu, pandas, datasets, transformers, evaluate
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.2 which is incompatible.
gradio 5.50.0 requires pandas<3.0,>=1.0, but you have pandas 3.0.2 which is incompatible.
bqplot 0.12.45 requires pandas<3.0.0,>=1.0.0, but you have pandas 3.0.2 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.2 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.2 which is incompatible.
db-dtypes 1.5.1 requires pandas<3.0.0,>=1.5.3, but you have pandas 3.0.2 which is incompatible.
Successfully installed colorama-0.4.6 datasets-4.8.5 evaluate-0.4.6 pandas-3.0.2 portalocker-3.2.0 psycopg2-binary-2.9.12 pyarrow-24.0.0 sacrebleu-2.6.0 sacremoses-0.1.1 torchao-0.17.0 transformers-5.7.0

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from datasets import Dataset

# 1. Chuỗi kết nối
DB_URL = "postgresql://postgres.jkaazcjahfqozwizhpvk:Khaiphadulieu@aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres"

print("Đang kết nối tới Supabase...")
engine = create_engine(DB_URL)

# 2. Truy vấn dữ liệu theo Chunk
chunk_size = 50000
query = "SELECT english_text, vietnamese_text FROM raw_data WHERE english_text IS NOT NULL AND vietnamese_text IS NOT NULL;"

print("Bắt đầu tải dữ liệu từ kho...")
try:
    chunks = pd.read_sql_query(query, engine, chunksize=chunk_size)

    df_list = []
    for i, chunk in enumerate(chunks):
        chunk = chunk.dropna()
        df_list.append(chunk)
        if (i+1) % 5 == 0:
            print(f"✅ Đã tải xong phần {i+1}")

    full_df = pd.concat(df_list, ignore_index=True)
    print(f"\n TỔNG SỐ CÂU GỐC: {len(full_df)}")

    target_size = 600000
    if len(full_df) > target_size:
        print(f"Đang lấy ngẫu nhiên {target_size} dòng để tối ưu tốc độ train...")
        full_df = full_df.sample(n=target_size, random_state=42).reset_index(drop=True)

    print(f"✅ SỐ LƯỢNG DÙNG ĐỂ TRAIN: {len(full_df)}")

    # 3. ÉP CÂN DỮ LIỆU BẰNG HUGGING FACE DATASET
    print("Đang ép kiểu dữ liệu sang Hugging Face format...")
    hf_dataset = Dataset.from_pandas(full_df)

    print("\n Xem thử 3 mẫu dữ liệu đầu tiên:")
    print(hf_dataset[:3])

except Exception as e:
    print(f"\n❌ Lỗi: {e}")

Đang kết nối tới Supabase...
Bắt đầu tải dữ liệu từ kho...
✅ Đã tải xong phần 5
✅ Đã tải xong phần 10

 TỔNG SỐ CÂU GỐC: 600000
✅ SỐ LƯỢNG DÙNG ĐỂ TRAIN: 600000
Đang ép kiểu dữ liệu sang Hugging Face format...

 Xem thử 3 mẫu dữ liệu đầu tiên:
{'english_text': ['In the summer 1990, the club was renamed Associazione Calcio Venezia 1907.', 'All right. IM: Do you have a problem looking cute?', 'Many systems have similar capabilities but different keywords, such as "null" (e.g. SQL), "NUL", "nil", and "None" (Python).'], 'vietnamese_text': ['Mùa hè năm 1990, câu lạc bộ được đổi tên thành Associazione Calcio Venezia 1907.', 'Được rồi IM: Cô có vấn đề với việc trông duyên dáng không?', 'Nhiều hệ thống có khả năng tương tự, nhưng khác nhau, từ khoá, như "vô" (như SQL), "NUL", "không" và "Không" (Python).']}

In [ ]:
from transformers import AutoTokenizer

# 1. Chọn model chuẩn cho dịch Anh-Việt làm Tokenizer
checkpoint = "Helsinki-NLP/opus-mt-en-vi"
print(f"Đang tải Tokenizer từ: {checkpoint}...")
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

# 2. Chia tập dữ liệu (95% Train - 5% Validation)
print("Đang chia tập Train và Validation...")
split_datasets = hf_dataset.train_test_split(test_size=0.05, seed=42)

# 3. Hàm tiền xử lý (Tokenization)
max_length = 64

def preprocess_function(examples):
    inputs = examples["english_text"]
    targets = examples["vietnamese_text"]

    model_inputs = tokenizer(inputs, max_length=max_length, truncation=True)
    labels = tokenizer(text_target=targets, max_length=max_length, truncation=True)

    model_inputs["labels"] = labels["input_ids"]
    return model_inputs

# 4. Áp dụng hàm trên cho toàn bộ dữ liệu
print("Bắt đầu Tokenize (Biến chữ thành số) - Quá trình này sẽ mất vài phút để xử lý 1.8 triệu câu...")
tokenized_datasets = split_datasets.map(
    preprocess_function,
    batched=True,
    num_proc=4,
    remove_columns=split_datasets["train"].column_names,
    desc="Đang Tokenize dữ liệu"
)

print("\n Tokenize thành công! Cấu trúc dữ liệu mới:")
print(tokenized_datasets)

# 5. LƯU VÀO Ổ CỨNG COLAB
print("\nĐang lưu dữ liệu đã tokenize vào ổ đĩa Colab...")
tokenized_datasets.save_to_disk("tokenized_en_vi_data")
print("✅ Đã lưu xong! Lần sau mở Colab chỉ cần load lại thư mục 'tokenized_en_vi_data' là xong, không phải kết nối Supabase hay Tokenize lại nữa.")

Đang tải Tokenizer từ: Helsinki-NLP/opus-mt-en-vi...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json: 0.00B [00:00, ?B/s]

tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/809k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/756k [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

Đang chia tập Train và Validation...
Bắt đầu Tokenize (Biến chữ thành số) - Quá trình này sẽ mất vài phút để xử lý 1.8 triệu câu...

Đang Tokenize dữ liệu (num_proc=4):   0%|          | 0/570000 [00:00<?, ? examples/s]

Đang Tokenize dữ liệu (num_proc=4):   0%|          | 0/30000 [00:00<?, ? examples/s]

 Tokenize thành công! Cấu trúc dữ liệu mới:
DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 570000
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 30000
    })
})

Đang lưu dữ liệu đã tokenize vào ổ đĩa Colab...

Saving the dataset (0/1 shards):   0%|          | 0/570000 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/30000 [00:00<?, ? examples/s]

✅ Đã lưu xong! Lần sau mở Colab chỉ cần load lại thư mục 'tokenized_en_vi_data' là xong, không phải kết nối Supabase hay Tokenize lại nữa.

In [ ]:
import numpy as np
import evaluate
from transformers import AutoModelForSeq2SeqLM, DataCollatorForSeq2Seq, Seq2SeqTrainingArguments, Seq2SeqTrainer
from peft import LoraConfig, get_peft_model, TaskType

# 1. Tải mô hình lõi (Base Model) vào GPU
checkpoint = "Helsinki-NLP/opus-mt-en-vi"
print("Đang tải Base Model...")
model = AutoModelForSeq2SeqLM.from_pretrained(checkpoint)

# A. Đóng băng Encoder
for param in model.get_encoder().parameters():
    param.requires_grad = False

# B. Áp dụng LoRA
peft_config = LoraConfig(
    task_type=TaskType.SEQ_2_SEQ_LM,
    inference_mode=False,
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"]
)

model = get_peft_model(model, peft_config)
model.print_trainable_parameters()


# 2. Data Collator: Tự động đệm (padding) các câu cho bằng nhau trong mỗi lượt train (Tiết kiệm RAM)
data_collator = DataCollatorForSeq2Seq(tokenizer=tokenizer, model=model)

# 3. Cài đặt công cụ tính điểm BLEU
metric = evaluate.load("sacrebleu")

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    if isinstance(preds, tuple):
        preds = preds[0]

    decoded_preds = tokenizer.batch_decode(preds, skip_special_tokens=True)

    labels = np.where(labels != -100, labels, tokenizer.pad_token_id)
    decoded_labels = tokenizer.batch_decode(labels, skip_special_tokens=True)

    decoded_labels = [[label] for label in decoded_labels]

    result = metric.compute(predictions=decoded_preds, references=decoded_labels)
    return {"bleu": result["score"]}

# 4. TỐI ƯU HÓA SIÊU THAM SỐ CHO COLAB
print("Đang thiết lập thông số huấn luyện tối ưu...")
training_args = Seq2SeqTrainingArguments(
    output_dir="./en_vi_translation_model",
    eval_strategy="epoch",
    learning_rate=2e-4,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=16,
    weight_decay=0.01,
    save_total_limit=2,
    num_train_epochs=3,
    predict_with_generate=True,
    fp16=True,
    gradient_accumulation_steps=2,
    dataloader_num_workers=2,
    logging_steps=200,
)

# 5. Ép cân tập Validation
print("Đang rút gọn tập Validation...")
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(2000))

# 6. Lắp ráp cỗ máy Trainer
print("Đang lắp ráp Trainer...")
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=small_eval_dataset,
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("\n LẮP RÁP THÀNH CÔNG! HỆ THỐNG ĐÃ SẴN SÀNG HUẤN LUYỆN.")

# 7. BẤM NÚT KHỞI ĐỘNG (TRAINING)
print("Bắt đầu quá trình huấn luyện (Fine-tuning)... GPU")
trainer.train()

# 8. LƯU MÔ HÌNH SAU KHI TRAIN XONG (Để chuẩn bị đẩy lên Hugging Face)
print("Đang lưu mô hình hoàn chỉnh...")
trainer.save_model("./en_vi_translation_model_final")
print("ĐÃ HOÀN THÀNH TOÀN BỘ QUÁ TRÌNH HUẤN LUYỆN!")

WARNING:torchao:Skipping import of cpp extensions due to incompatible torch version. Please upgrade to torch >= 2.11.0 (found 2.10.0+cu128).

Đang tải Base Model...

pytorch_model.bin:   0%|          | 0.00/289M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/289M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

trainable params: 294,912 || all params: 72,444,416 || trainable%: 0.4071

Downloading builder script: 0.00B [00:00, ?B/s]

Đang thiết lập thông số huấn luyện tối ưu...

[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'bos_token_id': None}.

Đang rút gọn tập Validation...
Đang lắp ráp Trainer...

 LẮP RÁP THÀNH CÔNG! HỆ THỐNG ĐÃ SẴN SÀNG HUẤN LUYỆN.
Bắt đầu quá trình huấn luyện (Fine-tuning)... GPU

Đang lưu mô hình hoàn chỉnh...
ĐÃ HOÀN THÀNH TOÀN BỘ QUÁ TRÌNH HUẤN LUYỆN!

In [ ]:
import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from peft import PeftModel

# 1. Định nghĩa đường dẫn
base_model_name = "Helsinki-NLP/opus-mt-en-vi"
adapter_path = "./en_vi_translation_model_final"

# 2. Tải Base Model và Tokenizer
print("Đang tải lại Base Model gốc...")
en_vi_tokenizer = AutoTokenizer.from_pretrained(base_model_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(base_model_name)

# 3. Gộp LoRA Adapter vào Base Model
print("Đang gộp bản vá LoRA vào Base Model (Merge Weights)...")
model_to_merge = PeftModel.from_pretrained(base_model, adapter_path)
merged_en_vi_model = model_to_merge.merge_and_unload() # Lệnh quan trọng nhất để xuất xưởng

# 4. Lưu lại Model ĐÃ GỢP để chuẩn bị cho TFLite
merged_model_path = "./merged_en_vi_model"
merged_en_vi_model.save_pretrained(merged_model_path)
en_vi_tokenizer.save_pretrained(merged_model_path)
print(f"✅ Đã lưu model HOÀN CHỈNH tại thư mục: {merged_model_path}")

# 5. TẠO HÀM DỊCH ANH -> VIỆT (TÁI SỬ DỤNG)
def dich_anh_viet(cau_tieng_anh):
    inputs = en_vi_tokenizer(cau_tieng_anh, return_tensors="pt")
    outputs = merged_en_vi_model.generate(**inputs, max_length=64)
    return en_vi_tokenizer.decode(outputs[0], skip_special_tokens=True)

# Test thử hàm
print("\n BẮT ĐẦU DỊCH THỬ:")
cau_test = "Knowledge Graph combined with Edge AI is a powerful weapon for our project."
ket_qua = dich_anh_viet(cau_test)

print(f"🇺🇸 Tiếng Anh: {cau_test}")
print(f"🇻🇳 Tiếng Việt: {ket_qua}")

Đang tải lại Base Model gốc...

Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

Đang gộp bản vá LoRA vào Base Model (Merge Weights)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Đã lưu model HOÀN CHỈNH tại thư mục: ./merged_en_vi_model

 BẮT ĐẦU DỊCH THỬ:
🇺🇸 Tiếng Anh: Knowledge Graph combined with Edge AI is a powerful weapon for our project.
🇻🇳 Tiếng Việt: Đồ thị tri thức kết hợp với Edge Al là một vũ khí mạnh mẽ cho dự án của chúng tôi.

In [ ]:
print(dich_anh_viet("I feel tired"))
print(dich_anh_viet("I love you"))

Tôi cảm thấy mệt mỏi
Anh yêu em

In [ ]:
from huggingface_hub import notebook_login

# Khi chạy sẽ hiện ô nhập Token.
# Bạn lấy Token (quyền WRITE) tại: https://huggingface.co/settings/tokens
notebook_login()
#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

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [ ]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

# 1.
repo_name_en_vi = "Dich-Thuat-AI-Nhom-05/en-vi-translator"

print("Đang tải mô hình En-Vi đã gộp sẵn từ Colab...")
# Trỏ vào thư mục đã lưu model hoàn chỉnh
merged_dir_en_vi = "./merged_en_vi_model"

# Tải Model và Tokenizer từ thư mục cục bộ
model_en_vi = AutoModelForSeq2SeqLM.from_pretrained(merged_dir_en_vi)
tokenizer_en_vi = AutoTokenizer.from_pretrained(merged_dir_en_vi)

# 3. Đẩy lên Hugging Face
print(f"Đang đẩy mô hình En-Vi lên: {repo_name_en_vi} (có thể mất vài phút)...")
model_en_vi.push_to_hub(repo_name_en_vi)
tokenizer_en_vi.push_to_hub(repo_name_en_vi)

print("Hoàn thành! Đã đẩy thành công mô hình Anh-Việt lên kho của Nhóm 05.")

Đang tải mô hình En-Vi đã gộp sẵn từ Colab...

Loading weights:   0%|          | 0/254 [00:00<?, ?it/s]

Đang đẩy mô hình En-Vi lên: Dich-Thuat-AI-Nhom-05/en-vi-translator (có thể mất vài phút)...

README.md: 0.00B [00:00, ?B/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...875nkon/model.safetensors:   0%|          |  138kB /  287MB

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /tmp/tmpb2khu1nh/target.spm : 100%|##########|  756kB /  756kB

  /tmp/tmpb2khu1nh/source.spm : 100%|##########|  809kB /  809kB

Hoàn thành! Đã đẩy thành công mô hình Anh-Việt lên kho của Nhóm 05.